/**
 * Theme Presets
 * Pre-configured themes for quick application
 */

export interface ThemePreset {
  id: string;
  name: string;
  description: string;
  author: string;
  tokens: Record<string, string>;
}

export const THEME_PRESETS: ThemePreset[] = [
  {
    id: 'material',
    name: 'Material Design',
    description: 'Inspired by Google Material Design with vibrant blues',
    author: 'Google',
    tokens: {
      '--semantic-brand-primary': '#1976d2',
      '--semantic-brand-secondary': '#424242',
      '--semantic-brand-subtle': '#e3f2fd',
      '--semantic-success-primary': '#388e3c',
      '--semantic-warning-primary': '#f57c00',
      '--semantic-error-primary': '#d32f2f',
      '--semantic-info-primary': '#0288d1',
      '--semantic-surface-background': '#fafafa',
      '--semantic-surface-card': '#ffffff',
      '--semantic-surface-subtle': '#f5f5f5',
      '--semantic-text-primary': '#212121',
      '--semantic-text-secondary': '#757575',
      '--semantic-text-tertiary': '#9e9e9e',
      '--primitive-font-family-base':
        '"Roboto", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      '--primitive-font-size-xs': '0.75rem',
      '--primitive-font-size-sm': '0.875rem',
      '--primitive-font-size-md': '1rem',
      '--primitive-font-size-lg': '1.25rem',
      '--primitive-font-size-xl': '1.5rem',
      '--primitive-spacing-1': '4px',
      '--primitive-spacing-2': '8px',
      '--primitive-spacing-3': '12px',
      '--primitive-spacing-4': '16px',
      '--primitive-spacing-6': '24px',
      '--primitive-spacing-8': '32px',
      '--primitive-border-radius-sm': '2px',
      '--primitive-border-radius-md': '4px',
      '--primitive-border-radius-lg': '8px',
      '--primitive-border-radius-full': '9999px',
    },
  },
  {
    id: 'bootstrap',
    name: 'Bootstrap',
    description: 'Classic Bootstrap theme with purple accents',
    author: 'Twitter',
    tokens: {
      '--semantic-brand-primary': '#6f42c1',
      '--semantic-brand-secondary': '#6c757d',
      '--semantic-brand-subtle': '#e7e3f5',
      '--semantic-success-primary': '#28a745',
      '--semantic-warning-primary': '#ffc107',
      '--semantic-error-primary': '#dc3545',
      '--semantic-info-primary': '#17a2b8',
      '--semantic-surface-background': '#ffffff',
      '--semantic-surface-card': '#f8f9fa',
      '--semantic-surface-subtle': '#e9ecef',
      '--semantic-text-primary': '#212529',
      '--semantic-text-secondary': '#6c757d',
      '--semantic-text-tertiary': '#adb5bd',
      '--primitive-font-family-base': '"Helvetica Neue", Arial, sans-serif',
      '--primitive-font-size-xs': '0.75rem',
      '--primitive-font-size-sm': '0.875rem',
      '--primitive-font-size-md': '1rem',
      '--primitive-font-size-lg': '1.25rem',
      '--primitive-font-size-xl': '1.5rem',
      '--primitive-spacing-1': '4px',
      '--primitive-spacing-2': '8px',
      '--primitive-spacing-3': '12px',
      '--primitive-spacing-4': '16px',
      '--primitive-spacing-6': '24px',
      '--primitive-spacing-8': '32px',
      '--primitive-border-radius-sm': '0.2rem',
      '--primitive-border-radius-md': '0.25rem',
      '--primitive-border-radius-lg': '0.3rem',
      '--primitive-border-radius-full': '50rem',
    },
  },
  {
    id: 'dark',
    name: 'Dark',
    description: 'Modern dark theme optimized for low-light environments',
    author: 'Community',
    tokens: {
      '--semantic-brand-primary': '#60a5fa',
      '--semantic-brand-secondary': '#94a3b8',
      '--semantic-brand-subtle': '#1e3a5f',
      '--semantic-success-primary': '#34d399',
      '--semantic-warning-primary': '#fbbf24',
      '--semantic-error-primary': '#f87171',
      '--semantic-info-primary': '#38bdf8',
      '--semantic-surface-background': '#0f172a',
      '--semantic-surface-card': '#1e293b',
      '--semantic-surface-subtle': '#334155',
      '--semantic-text-primary': '#f1f5f9',
      '--semantic-text-secondary': '#cbd5e1',
      '--semantic-text-tertiary': '#94a3b8',
      '--primitive-font-family-base':
        '"Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      '--primitive-font-size-xs': '0.75rem',
      '--primitive-font-size-sm': '0.875rem',
      '--primitive-font-size-md': '1rem',
      '--primitive-font-size-lg': '1.125rem',
      '--primitive-font-size-xl': '1.5rem',
      '--primitive-spacing-1': '4px',
      '--primitive-spacing-2': '8px',
      '--primitive-spacing-3': '12px',
      '--primitive-spacing-4': '16px',
      '--primitive-spacing-6': '24px',
      '--primitive-spacing-8': '32px',
      '--primitive-border-radius-sm': '4px',
      '--primitive-border-radius-md': '6px',
      '--primitive-border-radius-lg': '8px',
      '--primitive-border-radius-full': '9999px',
    },
  },
  {
    id: 'minimal',
    name: 'Minimal',
    description: 'Clean and minimal design with subtle grays',
    author: 'Community',
    tokens: {
      '--semantic-brand-primary': '#000000',
      '--semantic-brand-secondary': '#666666',
      '--semantic-brand-subtle': '#f5f5f5',
      '--semantic-success-primary': '#10b981',
      '--semantic-warning-primary': '#f59e0b',
      '--semantic-error-primary': '#ef4444',
      '--semantic-info-primary': '#3b82f6',
      '--semantic-surface-background': '#ffffff',
      '--semantic-surface-card': '#fafafa',
      '--semantic-surface-subtle': '#f5f5f5',
      '--semantic-text-primary': '#000000',
      '--semantic-text-secondary': '#666666',
      '--semantic-text-tertiary': '#999999',
      '--primitive-font-family-base':
        '"Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      '--primitive-font-size-xs': '0.75rem',
      '--primitive-font-size-sm': '0.875rem',
      '--primitive-font-size-md': '1rem',
      '--primitive-font-size-lg': '1.125rem',
      '--primitive-font-size-xl': '1.5rem',
      '--primitive-spacing-1': '4px',
      '--primitive-spacing-2': '8px',
      '--primitive-spacing-3': '12px',
      '--primitive-spacing-4': '16px',
      '--primitive-spacing-6': '24px',
      '--primitive-spacing-8': '32px',
      '--primitive-border-radius-sm': '2px',
      '--primitive-border-radius-md': '4px',
      '--primitive-border-radius-lg': '6px',
      '--primitive-border-radius-full': '9999px',
    },
  },
  {
    id: 'high-contrast',
    name: 'High Contrast',
    description: 'Maximum accessibility with WCAG AAA contrast',
    author: 'Accessibility Team',
    tokens: {
      '--semantic-brand-primary': '#0066cc',
      '--semantic-brand-secondary': '#333333',
      '--semantic-brand-subtle': '#e6f2ff',
      '--semantic-success-primary': '#006600',
      '--semantic-warning-primary': '#996600',
      '--semantic-error-primary': '#cc0000',
      '--semantic-info-primary': '#004d99',
      '--semantic-surface-background': '#ffffff',
      '--semantic-surface-card': '#f0f0f0',
      '--semantic-surface-subtle': '#e0e0e0',
      '--semantic-text-primary': '#000000',
      '--semantic-text-secondary': '#333333',
      '--semantic-text-tertiary': '#666666',
      '--primitive-font-family-base':
        '-apple-system, BlinkMacSystemFont, "Segoe UI", Arial, sans-serif',
      '--primitive-font-size-xs': '0.875rem',
      '--primitive-font-size-sm': '1rem',
      '--primitive-font-size-md': '1.125rem',
      '--primitive-font-size-lg': '1.25rem',
      '--primitive-font-size-xl': '1.5rem',
      '--primitive-spacing-1': '6px',
      '--primitive-spacing-2': '12px',
      '--primitive-spacing-3': '16px',
      '--primitive-spacing-4': '20px',
      '--primitive-spacing-6': '28px',
      '--primitive-spacing-8': '36px',
      '--primitive-border-radius-sm': '2px',
      '--primitive-border-radius-md': '4px',
      '--primitive-border-radius-lg': '6px',
      '--primitive-border-radius-full': '9999px',
    },
  },
  {
    id: 'ocean',
    name: 'Ocean',
    description: 'Calm and serene with ocean-inspired blues and teals',
    author: 'Community',
    tokens: {
      '--semantic-brand-primary': '#0891b2',
      '--semantic-brand-secondary': '#0e7490',
      '--semantic-brand-subtle': '#cffafe',
      '--semantic-success-primary': '#059669',
      '--semantic-warning-primary': '#f59e0b',
      '--semantic-error-primary': '#dc2626',
      '--semantic-info-primary': '#06b6d4',
      '--semantic-surface-background': '#f0fdfa',
      '--semantic-surface-card': '#ffffff',
      '--semantic-surface-subtle': '#ccfbf1',
      '--semantic-text-primary': '#134e4a',
      '--semantic-text-secondary': '#115e59',
      '--semantic-text-tertiary': '#5eead4',
      '--primitive-font-family-base':
        '"Open Sans", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      '--primitive-font-size-xs': '0.75rem',
      '--primitive-font-size-sm': '0.875rem',
      '--primitive-font-size-md': '1rem',
      '--primitive-font-size-lg': '1.125rem',
      '--primitive-font-size-xl': '1.5rem',
      '--primitive-spacing-1': '4px',
      '--primitive-spacing-2': '8px',
      '--primitive-spacing-3': '12px',
      '--primitive-spacing-4': '16px',
      '--primitive-spacing-6': '24px',
      '--primitive-spacing-8': '32px',
      '--primitive-border-radius-sm': '4px',
      '--primitive-border-radius-md': '8px',
      '--primitive-border-radius-lg': '12px',
      '--primitive-border-radius-full': '9999px',
    },
  },
  {
    id: 'sunset',
    name: 'Sunset',
    description: 'Warm and vibrant with sunset-inspired oranges and reds',
    author: 'Community',
    tokens: {
      '--semantic-brand-primary': '#f97316',
      '--semantic-brand-secondary': '#ea580c',
      '--semantic-brand-subtle': '#ffedd5',
      '--semantic-success-primary': '#16a34a',
      '--semantic-warning-primary': '#eab308',
      '--semantic-error-primary': '#dc2626',
      '--semantic-info-primary': '#3b82f6',
      '--semantic-surface-background': '#fff7ed',
      '--semantic-surface-card': '#ffffff',
      '--semantic-surface-subtle': '#fed7aa',
      '--semantic-text-primary': '#431407',
      '--semantic-text-secondary': '#9a3412',
      '--semantic-text-tertiary': '#fb923c',
      '--primitive-font-family-base':
        '"Poppins", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      '--primitive-font-size-xs': '0.75rem',
      '--primitive-font-size-sm': '0.875rem',
      '--primitive-font-size-md': '1rem',
      '--primitive-font-size-lg': '1.125rem',
      '--primitive-font-size-xl': '1.5rem',
      '--primitive-spacing-1': '4px',
      '--primitive-spacing-2': '8px',
      '--primitive-spacing-3': '12px',
      '--primitive-spacing-4': '16px',
      '--primitive-spacing-6': '24px',
      '--primitive-spacing-8': '32px',
      '--primitive-border-radius-sm': '6px',
      '--primitive-border-radius-md': '8px',
      '--primitive-border-radius-lg': '12px',
      '--primitive-border-radius-full': '9999px',
    },
  },
  {
    id: 'frog',
    name: 'Frog',
    description: 'Fresh and vibrant with lily pad greens and wetland tones',
    author: 'Community',
    tokens: {
      '--semantic-brand-primary': '#22c55e',
      '--semantic-brand-secondary': '#16a34a',
      '--semantic-brand-subtle': '#dcfce7',
      '--semantic-success-primary': '#4ade80',
      '--semantic-warning-primary': '#fbbf24',
      '--semantic-error-primary': '#ef4444',
      '--semantic-info-primary': '#06b6d4',
      '--semantic-surface-background': '#f0fdf4',
      '--semantic-surface-card': '#ffffff',
      '--semantic-surface-subtle': '#bbf7d0',
      '--semantic-text-primary': '#14532d',
      '--semantic-text-secondary': '#166534',
      '--semantic-text-tertiary': '#4ade80',
      '--primitive-font-family-base': '"Comic Neue", "Comic Sans MS", cursive, sans-serif',
      '--primitive-font-size-xs': '0.75rem',
      '--primitive-font-size-sm': '0.875rem',
      '--primitive-font-size-md': '1rem',
      '--primitive-font-size-lg': '1.125rem',
      '--primitive-font-size-xl': '1.5rem',
      '--primitive-spacing-1': '4px',
      '--primitive-spacing-2': '8px',
      '--primitive-spacing-3': '12px',
      '--primitive-spacing-4': '16px',
      '--primitive-spacing-6': '24px',
      '--primitive-spacing-8': '32px',
      '--primitive-border-radius-sm': '8px',
      '--primitive-border-radius-md': '12px',
      '--primitive-border-radius-lg': '16px',
      '--primitive-border-radius-full': '9999px',
    },
  },
  {
    id: 'axolotl',
    name: 'Axolotl',
    description: 'Playful and cute with pink coral tones and aquatic vibes',
    author: 'Community',
    tokens: {
      '--semantic-brand-primary': '#f472b6',
      '--semantic-brand-secondary': '#ec4899',
      '--semantic-brand-subtle': '#fce7f3',
      '--semantic-success-primary': '#10b981',
      '--semantic-warning-primary': '#f59e0b',
      '--semantic-error-primary': '#ef4444',
      '--semantic-info-primary': '#06b6d4',
      '--semantic-surface-background': '#fdf2f8',
      '--semantic-surface-card': '#ffffff',
      '--semantic-surface-subtle': '#fbcfe8',
      '--semantic-text-primary': '#831843',
      '--semantic-text-secondary': '#9f1239',
      '--semantic-text-tertiary': '#f472b6',
      '--primitive-font-family-base': '"Nunito", "Comic Sans MS", cursive, sans-serif',
      '--primitive-font-size-xs': '0.75rem',
      '--primitive-font-size-sm': '0.875rem',
      '--primitive-font-size-md': '1rem',
      '--primitive-font-size-lg': '1.125rem',
      '--primitive-font-size-xl': '1.5rem',
      '--primitive-spacing-1': '4px',
      '--primitive-spacing-2': '8px',
      '--primitive-spacing-3': '12px',
      '--primitive-spacing-4': '16px',
      '--primitive-spacing-6': '24px',
      '--primitive-spacing-8': '32px',
      '--primitive-border-radius-sm': '10px',
      '--primitive-border-radius-md': '14px',
      '--primitive-border-radius-lg': '18px',
      '--primitive-border-radius-full': '9999px',
    },
  },
];
