/**
 * Theme Presets
 * Pre-configured theme families for quick application
 */

export type ThemePresetTokens = Record<string, string>;

export interface ThemePreset {
  id: string;
  name: string;
  description: string;
  author: string;
  light: ThemePresetTokens;
  dark: ThemePresetTokens;
  tokens: ThemePresetTokens;
}

interface ThemePresetDefinition {
  id: string;
  name: string;
  description: string;
  author: string;
  sharedTokens: ThemePresetTokens;
  lightTokens: ThemePresetTokens;
  darkTokens: ThemePresetTokens;
}

function createThemePreset(definition: ThemePresetDefinition): ThemePreset {
  const light = {
    ...definition.sharedTokens,
    ...definition.lightTokens,
  };
  const dark = {
    ...definition.sharedTokens,
    ...definition.darkTokens,
  };

  return {
    id: definition.id,
    name: definition.name,
    description: definition.description,
    author: definition.author,
    light,
    dark,
    tokens: light,
  };
}

const standardScaleTokens: ThemePresetTokens = {
  '--primitive-font-size-xs': '0.75rem',
  '--primitive-font-size-sm': '0.875rem',
  '--primitive-font-size-md': '1rem',
  '--primitive-font-size-lg': '1.125rem',
  '--primitive-font-size-xl': '1.5rem',
  '--primitive-spacing-1': '4px',
  '--primitive-spacing-2': '8px',
  '--primitive-spacing-3': '12px',
  '--primitive-spacing-4': '16px',
  '--primitive-spacing-6': '24px',
  '--primitive-spacing-8': '32px',
  '--primitive-border-radius-sm': '4px',
  '--primitive-border-radius-md': '8px',
  '--primitive-border-radius-lg': '12px',
  '--primitive-border-radius-full': '9999px',
};

const themePresetDefinitions: ThemePresetDefinition[] = [
  {
    id: 'material',
    name: 'Material Design',
    description: 'Inspired by Google Material Design with vibrant blues',
    author: 'Google',
    sharedTokens: {
      ...standardScaleTokens,
      '--primitive-font-family-base': '"Roboto", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      '--primitive-font-size-lg': '1.25rem',
      '--primitive-border-radius-sm': '2px',
      '--primitive-border-radius-md': '4px',
      '--primitive-border-radius-lg': '8px',
    },
    lightTokens: {
      '--semantic-brand-primary': '#1976d2',
      '--semantic-brand-secondary': '#424242',
      '--semantic-brand-subtle': '#e3f2fd',
      '--semantic-success-primary': '#388e3c',
      '--semantic-warning-primary': '#f57c00',
      '--semantic-error-primary': '#d32f2f',
      '--semantic-info-primary': '#0288d1',
      '--semantic-surface-background': '#fafafa',
      '--semantic-surface-card': '#ffffff',
      '--semantic-surface-subtle': '#f5f5f5',
      '--semantic-text-primary': '#212121',
      '--semantic-text-secondary': '#757575',
      '--semantic-text-tertiary': '#9e9e9e',
    },
    darkTokens: {
      '--semantic-brand-primary': '#90caf9',
      '--semantic-brand-secondary': '#b0bec5',
      '--semantic-brand-subtle': '#1e3a5f',
      '--semantic-success-primary': '#66bb6a',
      '--semantic-warning-primary': '#ffb74d',
      '--semantic-error-primary': '#ef5350',
      '--semantic-info-primary': '#4fc3f7',
      '--semantic-surface-background': '#121212',
      '--semantic-surface-card': '#1e1e1e',
      '--semantic-surface-subtle': '#2a2a2a',
      '--semantic-text-primary': '#f5f5f5',
      '--semantic-text-secondary': '#c7c7c7',
      '--semantic-text-tertiary': '#9e9e9e',
    },
  },
  {
    id: 'bootstrap',
    name: 'Bootstrap',
    description: 'Classic Bootstrap theme with purple accents',
    author: 'Twitter',
    sharedTokens: {
      ...standardScaleTokens,
      '--primitive-font-family-base': '"Helvetica Neue", Arial, sans-serif',
      '--primitive-font-size-lg': '1.25rem',
      '--primitive-border-radius-sm': '0.2rem',
      '--primitive-border-radius-md': '0.25rem',
      '--primitive-border-radius-lg': '0.3rem',
      '--primitive-border-radius-full': '50rem',
    },
    lightTokens: {
      '--semantic-brand-primary': '#6f42c1',
      '--semantic-brand-secondary': '#6c757d',
      '--semantic-brand-subtle': '#e7e3f5',
      '--semantic-success-primary': '#28a745',
      '--semantic-warning-primary': '#ffc107',
      '--semantic-error-primary': '#dc3545',
      '--semantic-info-primary': '#17a2b8',
      '--semantic-surface-background': '#ffffff',
      '--semantic-surface-card': '#f8f9fa',
      '--semantic-surface-subtle': '#e9ecef',
      '--semantic-text-primary': '#212529',
      '--semantic-text-secondary': '#6c757d',
      '--semantic-text-tertiary': '#adb5bd',
    },
    darkTokens: {
      '--semantic-brand-primary': '#b197fc',
      '--semantic-brand-secondary': '#ced4da',
      '--semantic-brand-subtle': '#2b223d',
      '--semantic-success-primary': '#51cf66',
      '--semantic-warning-primary': '#ffd43b',
      '--semantic-error-primary': '#ff6b6b',
      '--semantic-info-primary': '#66d9e8',
      '--semantic-surface-background': '#15171a',
      '--semantic-surface-card': '#212529',
      '--semantic-surface-subtle': '#343a40',
      '--semantic-text-primary': '#f8f9fa',
      '--semantic-text-secondary': '#ced4da',
      '--semantic-text-tertiary': '#adb5bd',
    },
  },
  {
    id: 'dark',
    name: 'Dark',
    description: 'Modern paired theme with slate light and dark variants',
    author: 'Community',
    sharedTokens: {
      ...standardScaleTokens,
      '--primitive-font-family-base': '"Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      '--primitive-border-radius-md': '6px',
      '--primitive-border-radius-lg': '8px',
    },
    lightTokens: {
      '--semantic-brand-primary': '#2563eb',
      '--semantic-brand-secondary': '#475569',
      '--semantic-brand-subtle': '#dbeafe',
      '--semantic-success-primary': '#16a34a',
      '--semantic-warning-primary': '#d97706',
      '--semantic-error-primary': '#dc2626',
      '--semantic-info-primary': '#0284c7',
      '--semantic-surface-background': '#f8fafc',
      '--semantic-surface-card': '#ffffff',
      '--semantic-surface-subtle': '#e2e8f0',
      '--semantic-text-primary': '#0f172a',
      '--semantic-text-secondary': '#475569',
      '--semantic-text-tertiary': '#64748b',
    },
    darkTokens: {
      '--semantic-brand-primary': '#60a5fa',
      '--semantic-brand-secondary': '#94a3b8',
      '--semantic-brand-subtle': '#1e3a5f',
      '--semantic-success-primary': '#34d399',
      '--semantic-warning-primary': '#fbbf24',
      '--semantic-error-primary': '#f87171',
      '--semantic-info-primary': '#38bdf8',
      '--semantic-surface-background': '#0f172a',
      '--semantic-surface-card': '#1e293b',
      '--semantic-surface-subtle': '#334155',
      '--semantic-text-primary': '#f1f5f9',
      '--semantic-text-secondary': '#cbd5e1',
      '--semantic-text-tertiary': '#94a3b8',
    },
  },
  {
    id: 'minimal',
    name: 'Minimal',
    description: 'Clean paired theme with restrained neutrals',
    author: 'Community',
    sharedTokens: {
      ...standardScaleTokens,
      '--primitive-font-family-base': '"Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      '--primitive-border-radius-sm': '2px',
      '--primitive-border-radius-md': '4px',
      '--primitive-border-radius-lg': '6px',
    },
    lightTokens: {
      '--semantic-brand-primary': '#000000',
      '--semantic-brand-secondary': '#666666',
      '--semantic-brand-subtle': '#f5f5f5',
      '--semantic-success-primary': '#10b981',
      '--semantic-warning-primary': '#f59e0b',
      '--semantic-error-primary': '#ef4444',
      '--semantic-info-primary': '#3b82f6',
      '--semantic-surface-background': '#ffffff',
      '--semantic-surface-card': '#fafafa',
      '--semantic-surface-subtle': '#f5f5f5',
      '--semantic-text-primary': '#000000',
      '--semantic-text-secondary': '#666666',
      '--semantic-text-tertiary': '#999999',
    },
    darkTokens: {
      '--semantic-brand-primary': '#ffffff',
      '--semantic-brand-secondary': '#d4d4d4',
      '--semantic-brand-subtle': '#262626',
      '--semantic-success-primary': '#34d399',
      '--semantic-warning-primary': '#fbbf24',
      '--semantic-error-primary': '#f87171',
      '--semantic-info-primary': '#60a5fa',
      '--semantic-surface-background': '#0a0a0a',
      '--semantic-surface-card': '#171717',
      '--semantic-surface-subtle': '#262626',
      '--semantic-text-primary': '#fafafa',
      '--semantic-text-secondary': '#d4d4d4',
      '--semantic-text-tertiary': '#a3a3a3',
    },
  },
  {
    id: 'high-contrast',
    name: 'High Contrast',
    description: 'Accessibility-first paired preset with explicit light and dark variants',
    author: 'Accessibility Team',
    sharedTokens: {
      ...standardScaleTokens,
      '--primitive-font-family-base': '-apple-system, BlinkMacSystemFont, "Segoe UI", Arial, sans-serif',
      '--primitive-font-size-xs': '0.875rem',
      '--primitive-font-size-sm': '1rem',
      '--primitive-font-size-md': '1.125rem',
      '--primitive-font-size-lg': '1.25rem',
      '--primitive-spacing-1': '6px',
      '--primitive-spacing-2': '12px',
      '--primitive-spacing-3': '16px',
      '--primitive-spacing-4': '20px',
      '--primitive-spacing-6': '28px',
      '--primitive-spacing-8': '36px',
      '--primitive-border-radius-sm': '2px',
      '--primitive-border-radius-md': '4px',
      '--primitive-border-radius-lg': '6px',
    },
    lightTokens: {
      '--semantic-brand-primary': '#0066cc',
      '--semantic-brand-secondary': '#333333',
      '--semantic-brand-subtle': '#e6f2ff',
      '--semantic-success-primary': '#006600',
      '--semantic-warning-primary': '#996600',
      '--semantic-error-primary': '#cc0000',
      '--semantic-info-primary': '#004d99',
      '--semantic-surface-background': '#ffffff',
      '--semantic-surface-card': '#f0f0f0',
      '--semantic-surface-subtle': '#e0e0e0',
      '--semantic-text-primary': '#000000',
      '--semantic-text-secondary': '#333333',
      '--semantic-text-tertiary': '#666666',
    },
    darkTokens: {
      '--semantic-brand-primary': '#66b2ff',
      '--semantic-brand-secondary': '#f5f5f5',
      '--semantic-brand-subtle': '#00264d',
      '--semantic-success-primary': '#66ff66',
      '--semantic-warning-primary': '#ffd24d',
      '--semantic-error-primary': '#ff8080',
      '--semantic-info-primary': '#80c7ff',
      '--semantic-surface-background': '#000000',
      '--semantic-surface-card': '#111111',
      '--semantic-surface-subtle': '#1f1f1f',
      '--semantic-text-primary': '#ffffff',
      '--semantic-text-secondary': '#f0f0f0',
      '--semantic-text-tertiary': '#c7c7c7',
    },
  },
  {
    id: 'ocean',
    name: 'Ocean',
    description: 'Calm paired theme with ocean-inspired blues and teals',
    author: 'Community',
    sharedTokens: {
      ...standardScaleTokens,
      '--primitive-font-family-base': '"Open Sans", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    },
    lightTokens: {
      '--semantic-brand-primary': '#0891b2',
      '--semantic-brand-secondary': '#0e7490',
      '--semantic-brand-subtle': '#cffafe',
      '--semantic-success-primary': '#059669',
      '--semantic-warning-primary': '#f59e0b',
      '--semantic-error-primary': '#dc2626',
      '--semantic-info-primary': '#06b6d4',
      '--semantic-surface-background': '#f0fdfa',
      '--semantic-surface-card': '#ffffff',
      '--semantic-surface-subtle': '#ccfbf1',
      '--semantic-text-primary': '#134e4a',
      '--semantic-text-secondary': '#115e59',
      '--semantic-text-tertiary': '#5eead4',
    },
    darkTokens: {
      '--semantic-brand-primary': '#22d3ee',
      '--semantic-brand-secondary': '#14b8a6',
      '--semantic-brand-subtle': '#123b3c',
      '--semantic-success-primary': '#34d399',
      '--semantic-warning-primary': '#fbbf24',
      '--semantic-error-primary': '#f87171',
      '--semantic-info-primary': '#38bdf8',
      '--semantic-surface-background': '#0b1f24',
      '--semantic-surface-card': '#12313a',
      '--semantic-surface-subtle': '#164e63',
      '--semantic-text-primary': '#e6fffb',
      '--semantic-text-secondary': '#99f6e4',
      '--semantic-text-tertiary': '#5eead4',
    },
  },
  {
    id: 'sunset',
    name: 'Sunset',
    description: 'Warm paired theme with sunset-inspired oranges and reds',
    author: 'Community',
    sharedTokens: {
      ...standardScaleTokens,
      '--primitive-font-family-base': '"Poppins", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      '--primitive-border-radius-sm': '6px',
      '--primitive-border-radius-md': '8px',
      '--primitive-border-radius-lg': '12px',
    },
    lightTokens: {
      '--semantic-brand-primary': '#f97316',
      '--semantic-brand-secondary': '#ea580c',
      '--semantic-brand-subtle': '#ffedd5',
      '--semantic-success-primary': '#16a34a',
      '--semantic-warning-primary': '#eab308',
      '--semantic-error-primary': '#dc2626',
      '--semantic-info-primary': '#3b82f6',
      '--semantic-surface-background': '#fff7ed',
      '--semantic-surface-card': '#ffffff',
      '--semantic-surface-subtle': '#fed7aa',
      '--semantic-text-primary': '#431407',
      '--semantic-text-secondary': '#9a3412',
      '--semantic-text-tertiary': '#fb923c',
    },
    darkTokens: {
      '--semantic-brand-primary': '#fb923c',
      '--semantic-brand-secondary': '#fdba74',
      '--semantic-brand-subtle': '#4a2612',
      '--semantic-success-primary': '#4ade80',
      '--semantic-warning-primary': '#facc15',
      '--semantic-error-primary': '#f87171',
      '--semantic-info-primary': '#60a5fa',
      '--semantic-surface-background': '#2a1408',
      '--semantic-surface-card': '#3b1d0f',
      '--semantic-surface-subtle': '#5b2a13',
      '--semantic-text-primary': '#fff7ed',
      '--semantic-text-secondary': '#fed7aa',
      '--semantic-text-tertiary': '#fdba74',
    },
  },
  {
    id: 'frog',
    name: 'Frog',
    description: 'Fresh paired theme with lily pad greens and wetland tones',
    author: 'Community',
    sharedTokens: {
      ...standardScaleTokens,
      '--primitive-font-family-base': '"Comic Neue", "Comic Sans MS", cursive, sans-serif',
      '--primitive-border-radius-sm': '8px',
      '--primitive-border-radius-md': '12px',
      '--primitive-border-radius-lg': '16px',
    },
    lightTokens: {
      '--semantic-brand-primary': '#22c55e',
      '--semantic-brand-secondary': '#16a34a',
      '--semantic-brand-subtle': '#dcfce7',
      '--semantic-success-primary': '#4ade80',
      '--semantic-warning-primary': '#fbbf24',
      '--semantic-error-primary': '#ef4444',
      '--semantic-info-primary': '#06b6d4',
      '--semantic-surface-background': '#f0fdf4',
      '--semantic-surface-card': '#ffffff',
      '--semantic-surface-subtle': '#bbf7d0',
      '--semantic-text-primary': '#14532d',
      '--semantic-text-secondary': '#166534',
      '--semantic-text-tertiary': '#4ade80',
    },
    darkTokens: {
      '--semantic-brand-primary': '#4ade80',
      '--semantic-brand-secondary': '#86efac',
      '--semantic-brand-subtle': '#17351f',
      '--semantic-success-primary': '#22c55e',
      '--semantic-warning-primary': '#fbbf24',
      '--semantic-error-primary': '#f87171',
      '--semantic-info-primary': '#22d3ee',
      '--semantic-surface-background': '#0d1f12',
      '--semantic-surface-card': '#163022',
      '--semantic-surface-subtle': '#1f4a30',
      '--semantic-text-primary': '#f0fdf4',
      '--semantic-text-secondary': '#bbf7d0',
      '--semantic-text-tertiary': '#86efac',
    },
  },
  {
    id: 'axolotl',
    name: 'Axolotl',
    description: 'Playful paired theme with pink coral tones and aquatic vibes',
    author: 'Community',
    sharedTokens: {
      ...standardScaleTokens,
      '--primitive-font-family-base': '"Nunito", "Comic Sans MS", cursive, sans-serif',
      '--primitive-border-radius-sm': '10px',
      '--primitive-border-radius-md': '14px',
      '--primitive-border-radius-lg': '18px',
    },
    lightTokens: {
      '--semantic-brand-primary': '#f472b6',
      '--semantic-brand-secondary': '#ec4899',
      '--semantic-brand-subtle': '#fce7f3',
      '--semantic-success-primary': '#10b981',
      '--semantic-warning-primary': '#f59e0b',
      '--semantic-error-primary': '#ef4444',
      '--semantic-info-primary': '#06b6d4',
      '--semantic-surface-background': '#fdf2f8',
      '--semantic-surface-card': '#ffffff',
      '--semantic-surface-subtle': '#fbcfe8',
      '--semantic-text-primary': '#831843',
      '--semantic-text-secondary': '#9f1239',
      '--semantic-text-tertiary': '#f472b6',
    },
    darkTokens: {
      '--semantic-brand-primary': '#f9a8d4',
      '--semantic-brand-secondary': '#f472b6',
      '--semantic-brand-subtle': '#4a1f33',
      '--semantic-success-primary': '#34d399',
      '--semantic-warning-primary': '#fbbf24',
      '--semantic-error-primary': '#f87171',
      '--semantic-info-primary': '#67e8f9',
      '--semantic-surface-background': '#2a1320',
      '--semantic-surface-card': '#3a1b2c',
      '--semantic-surface-subtle': '#4a1f38',
      '--semantic-text-primary': '#fdf2f8',
      '--semantic-text-secondary': '#fbcfe8',
      '--semantic-text-tertiary': '#f9a8d4',
    },
  },
];

export const THEME_PRESETS: ThemePreset[] = themePresetDefinitions.map(createThemePreset);
