/**
 * Theme Presets
 * Pre-configured theme families for quick application
 */

export type ThemePresetTokens = Record<string, string>;

export interface ThemePreset {
  id: string;
  name: string;
  description: string;
  author: string;
  light: ThemePresetTokens;
  dark: ThemePresetTokens;
  tokens: ThemePresetTokens;
}

interface ThemePresetDefinition {
  id: string;
  name: string;
  description: string;
  author: string;
  sharedTokens: ThemePresetTokens;
  lightTokens: ThemePresetTokens;
  darkTokens: ThemePresetTokens;
}

function createThemePreset(definition: ThemePresetDefinition): ThemePreset {
  const light = {
    ...definition.sharedTokens,
    ...definition.lightTokens,
  };
  const dark = {
    ...definition.sharedTokens,
    ...definition.darkTokens,
  };

  return {
    id: definition.id,
    name: definition.name,
    description: definition.description,
    author: definition.author,
    light,
    dark,
    tokens: light,
  };
}

const standardScaleTokens: ThemePresetTokens = {
  '--primitive-font-size-xs': '0.75rem',
  '--primitive-font-size-sm': '0.875rem',
  '--primitive-font-size-base': '1rem',
  '--primitive-font-size-lg': '1.125rem',
  '--primitive-font-size-xl': '1.5rem',
  '--primitive-spacing-1': '4px',
  '--primitive-spacing-2': '8px',
  '--primitive-spacing-3': '12px',
  '--primitive-spacing-4': '16px',
  '--primitive-spacing-6': '24px',
  '--primitive-spacing-8': '32px',
  '--primitive-border-radius-sm': '4px',
  '--primitive-border-radius-md': '8px',
  '--primitive-border-radius-lg': '12px',
  '--primitive-border-radius-full': '9999px',
};

const themePresetDefinitions: ThemePresetDefinition[] = [
  {
    id: 'material',
    name: 'Material Design',
    description: 'Inspired by Google Material Design with vibrant blues',
    author: 'Google',
    sharedTokens: {
      ...standardScaleTokens,
      '--primitive-font-family-sans':
        '"Roboto", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      '--primitive-font-size-lg': '1.25rem',
      '--primitive-border-radius-sm': '2px',
      '--primitive-border-radius-md': '4px',
      '--primitive-border-radius-lg': '8px',
    },
    lightTokens: {
      '--semantic-brand-primary': '#1565c0',
      '--semantic-brand-secondary': '#424242',
      '--semantic-brand-primary-subtle': '#e3f2fd',
      '--semantic-feedback-success': '#388e3c',
      '--semantic-feedback-warning': '#f57c00',
      '--semantic-feedback-error': '#d32f2f',
      '--semantic-feedback-info': '#0288d1',
      '--semantic-surface-background': '#fafafa',
      '--semantic-surface-card': '#ffffff',
      '--semantic-surface-background-secondary': '#f5f5f5',
      '--semantic-text-primary': '#212121',
      '--semantic-text-secondary': '#6d6d6d',
      '--semantic-text-tertiary': '#9e9e9e',
    },
    darkTokens: {
      '--semantic-brand-primary': '#90caf9',
      '--semantic-brand-secondary': '#b0bec5',
      '--semantic-brand-primary-subtle': '#1e3a5f',
      '--semantic-feedback-success': '#66bb6a',
      '--semantic-feedback-warning': '#ffb74d',
      '--semantic-feedback-error': '#ef5350',
      '--semantic-feedback-info': '#4fc3f7',
      '--semantic-surface-background': '#121212',
      '--semantic-surface-card': '#1e1e1e',
      '--semantic-surface-background-secondary': '#2a2a2a',
      '--semantic-text-primary': '#f5f5f5',
      '--semantic-text-secondary': '#c7c7c7',
      '--semantic-text-tertiary': '#9e9e9e',
    },
  },
  {
    id: 'bootstrap',
    name: 'Bootstrap',
    description: 'Classic Bootstrap theme with purple accents',
    author: 'Twitter',
    sharedTokens: {
      ...standardScaleTokens,
      '--primitive-font-family-sans': '"Helvetica Neue", Arial, sans-serif',
      '--primitive-font-size-lg': '1.25rem',
      '--primitive-border-radius-sm': '0.2rem',
      '--primitive-border-radius-md': '0.25rem',
      '--primitive-border-radius-lg': '0.3rem',
      '--primitive-border-radius-full': '50rem',
    },
    lightTokens: {
      '--semantic-brand-primary': '#6f42c1',
      '--semantic-brand-secondary': '#6c757d',
      '--semantic-brand-primary-subtle': '#e7e3f5',
      '--semantic-feedback-success': '#28a745',
      '--semantic-feedback-warning': '#ffc107',
      '--semantic-feedback-error': '#dc3545',
      '--semantic-feedback-info': '#17a2b8',
      '--semantic-surface-background': '#ffffff',
      '--semantic-surface-card': '#f8f9fa',
      '--semantic-surface-background-secondary': '#e9ecef',
      '--semantic-text-primary': '#212529',
      '--semantic-text-secondary': '#6c757d',
      '--semantic-text-tertiary': '#adb5bd',
    },
    darkTokens: {
      '--semantic-brand-primary': '#b197fc',
      '--semantic-brand-secondary': '#ced4da',
      '--semantic-brand-primary-subtle': '#2b223d',
      '--semantic-feedback-success': '#51cf66',
      '--semantic-feedback-warning': '#ffd43b',
      '--semantic-feedback-error': '#ff6b6b',
      '--semantic-feedback-info': '#66d9e8',
      '--semantic-surface-background': '#15171a',
      '--semantic-surface-card': '#212529',
      '--semantic-surface-background-secondary': '#343a40',
      '--semantic-text-primary': '#f8f9fa',
      '--semantic-text-secondary': '#ced4da',
      '--semantic-text-tertiary': '#adb5bd',
    },
  },
  {
    id: 'dark',
    name: 'Dark',
    description: 'Modern paired theme with slate light and dark variants',
    author: 'Community',
    sharedTokens: {
      ...standardScaleTokens,
      '--primitive-font-family-sans':
        '"Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      '--primitive-border-radius-md': '6px',
      '--primitive-border-radius-lg': '8px',
    },
    lightTokens: {
      '--semantic-brand-primary': '#2563eb',
      '--semantic-brand-secondary': '#475569',
      '--semantic-brand-primary-subtle': '#dbeafe',
      '--semantic-feedback-success': '#16a34a',
      '--semantic-feedback-warning': '#d97706',
      '--semantic-feedback-error': '#dc2626',
      '--semantic-feedback-info': '#0284c7',
      '--semantic-surface-background': '#f8fafc',
      '--semantic-surface-card': '#ffffff',
      '--semantic-surface-background-secondary': '#e2e8f0',
      '--semantic-text-primary': '#0f172a',
      '--semantic-text-secondary': '#475569',
      '--semantic-text-tertiary': '#64748b',
    },
    darkTokens: {
      '--semantic-brand-primary': '#60a5fa',
      '--semantic-brand-secondary': '#94a3b8',
      '--semantic-brand-primary-subtle': '#1e3a5f',
      '--semantic-feedback-success': '#34d399',
      '--semantic-feedback-warning': '#fbbf24',
      '--semantic-feedback-error': '#f87171',
      '--semantic-feedback-info': '#38bdf8',
      '--semantic-surface-background': '#0f172a',
      '--semantic-surface-card': '#1e293b',
      '--semantic-surface-background-secondary': '#334155',
      '--semantic-text-primary': '#f1f5f9',
      '--semantic-text-secondary': '#cbd5e1',
      '--semantic-text-tertiary': '#94a3b8',
    },
  },
  {
    id: 'minimal',
    name: 'Minimal',
    description: 'Clean paired theme with restrained neutrals',
    author: 'Community',
    sharedTokens: {
      ...standardScaleTokens,
      '--primitive-font-family-sans':
        '"Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      '--primitive-border-radius-sm': '2px',
      '--primitive-border-radius-md': '4px',
      '--primitive-border-radius-lg': '6px',
    },
    lightTokens: {
      '--semantic-brand-primary': '#000000',
      '--semantic-brand-secondary': '#666666',
      '--semantic-brand-primary-subtle': '#f5f5f5',
      '--semantic-feedback-success': '#10b981',
      '--semantic-feedback-warning': '#f59e0b',
      '--semantic-feedback-error': '#ef4444',
      '--semantic-feedback-info': '#3b82f6',
      '--semantic-surface-background': '#ffffff',
      '--semantic-surface-card': '#fafafa',
      '--semantic-surface-background-secondary': '#f5f5f5',
      '--semantic-text-primary': '#000000',
      '--semantic-text-secondary': '#666666',
      '--semantic-text-tertiary': '#999999',
    },
    darkTokens: {
      '--semantic-brand-primary': '#ffffff',
      '--semantic-brand-secondary': '#d4d4d4',
      '--semantic-brand-primary-subtle': '#262626',
      '--semantic-feedback-success': '#34d399',
      '--semantic-feedback-warning': '#fbbf24',
      '--semantic-feedback-error': '#f87171',
      '--semantic-feedback-info': '#60a5fa',
      '--semantic-surface-background': '#0a0a0a',
      '--semantic-surface-card': '#171717',
      '--semantic-surface-background-secondary': '#262626',
      '--semantic-text-primary': '#fafafa',
      '--semantic-text-secondary': '#d4d4d4',
      '--semantic-text-tertiary': '#a3a3a3',
    },
  },
  {
    id: 'high-contrast',
    name: 'High Contrast',
    description: 'Accessibility-first paired preset with explicit light and dark variants',
    author: 'Accessibility Team',
    sharedTokens: {
      ...standardScaleTokens,
      '--primitive-font-family-sans':
        '-apple-system, BlinkMacSystemFont, "Segoe UI", Arial, sans-serif',
      '--primitive-font-size-xs': '0.875rem',
      '--primitive-font-size-sm': '1rem',
      '--primitive-font-size-base': '1.125rem',
      '--primitive-font-size-lg': '1.25rem',
      '--primitive-spacing-1': '6px',
      '--primitive-spacing-2': '12px',
      '--primitive-spacing-3': '16px',
      '--primitive-spacing-4': '20px',
      '--primitive-spacing-6': '28px',
      '--primitive-spacing-8': '36px',
      '--primitive-border-radius-sm': '2px',
      '--primitive-border-radius-md': '4px',
      '--primitive-border-radius-lg': '6px',
    },
    lightTokens: {
      '--semantic-brand-primary': '#0066cc',
      '--semantic-brand-secondary': '#333333',
      '--semantic-brand-primary-subtle': '#e6f2ff',
      '--semantic-feedback-success': '#006600',
      '--semantic-feedback-warning': '#996600',
      '--semantic-feedback-error': '#cc0000',
      '--semantic-feedback-info': '#004d99',
      '--semantic-surface-background': '#ffffff',
      '--semantic-surface-card': '#f0f0f0',
      '--semantic-surface-background-secondary': '#e0e0e0',
      '--semantic-text-primary': '#000000',
      '--semantic-text-secondary': '#333333',
      '--semantic-text-tertiary': '#666666',
    },
    darkTokens: {
      '--semantic-brand-primary': '#66b2ff',
      '--semantic-brand-secondary': '#f5f5f5',
      '--semantic-brand-primary-subtle': '#00264d',
      '--semantic-feedback-success': '#66ff66',
      '--semantic-feedback-warning': '#ffd24d',
      '--semantic-feedback-error': '#ff8080',
      '--semantic-feedback-info': '#80c7ff',
      '--semantic-surface-background': '#000000',
      '--semantic-surface-card': '#111111',
      '--semantic-surface-background-secondary': '#1f1f1f',
      '--semantic-text-primary': '#ffffff',
      '--semantic-text-secondary': '#f0f0f0',
      '--semantic-text-tertiary': '#c7c7c7',
    },
  },
  {
    id: 'ocean',
    name: 'Ocean',
    description: 'Calm paired theme with ocean-inspired blues and teals',
    author: 'Community',
    sharedTokens: {
      ...standardScaleTokens,
      '--primitive-font-family-sans':
        '"Open Sans", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    },
    lightTokens: {
      '--semantic-brand-primary': '#0e7490',
      '--semantic-brand-secondary': '#0e7490',
      '--semantic-brand-primary-subtle': '#cffafe',
      '--semantic-feedback-success': '#059669',
      '--semantic-feedback-warning': '#f59e0b',
      '--semantic-feedback-error': '#dc2626',
      '--semantic-feedback-info': '#06b6d4',
      '--semantic-surface-background': '#f0fdfa',
      '--semantic-surface-card': '#ffffff',
      '--semantic-surface-background-secondary': '#ccfbf1',
      '--semantic-text-primary': '#134e4a',
      '--semantic-text-secondary': '#115e59',
      '--semantic-text-tertiary': '#5eead4',
    },
    darkTokens: {
      '--semantic-brand-primary': '#22d3ee',
      '--semantic-brand-secondary': '#14b8a6',
      '--semantic-brand-primary-subtle': '#123b3c',
      '--semantic-feedback-success': '#34d399',
      '--semantic-feedback-warning': '#fbbf24',
      '--semantic-feedback-error': '#f87171',
      '--semantic-feedback-info': '#38bdf8',
      '--semantic-surface-background': '#0b1f24',
      '--semantic-surface-card': '#12313a',
      '--semantic-surface-background-secondary': '#164e63',
      '--semantic-text-primary': '#e6fffb',
      '--semantic-text-secondary': '#99f6e4',
      '--semantic-text-tertiary': '#5eead4',
    },
  },
  {
    id: 'sunset',
    name: 'Sunset',
    description: 'Warm paired theme with sunset-inspired oranges and reds',
    author: 'Community',
    sharedTokens: {
      ...standardScaleTokens,
      '--primitive-font-family-sans':
        '"Poppins", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      '--primitive-border-radius-sm': '6px',
      '--primitive-border-radius-md': '8px',
      '--primitive-border-radius-lg': '12px',
    },
    lightTokens: {
      '--semantic-brand-primary': '#c2410c',
      '--semantic-brand-secondary': '#ea580c',
      '--semantic-brand-primary-subtle': '#ffedd5',
      '--semantic-feedback-success': '#16a34a',
      '--semantic-feedback-warning': '#eab308',
      '--semantic-feedback-error': '#dc2626',
      '--semantic-feedback-info': '#3b82f6',
      '--semantic-surface-background': '#fff7ed',
      '--semantic-surface-card': '#ffffff',
      '--semantic-surface-background-secondary': '#fed7aa',
      '--semantic-text-primary': '#431407',
      '--semantic-text-secondary': '#9a3412',
      '--semantic-text-tertiary': '#fb923c',
    },
    darkTokens: {
      '--semantic-brand-primary': '#fb923c',
      '--semantic-brand-secondary': '#fdba74',
      '--semantic-brand-primary-subtle': '#4a2612',
      '--semantic-feedback-success': '#4ade80',
      '--semantic-feedback-warning': '#facc15',
      '--semantic-feedback-error': '#f87171',
      '--semantic-feedback-info': '#60a5fa',
      '--semantic-surface-background': '#2a1408',
      '--semantic-surface-card': '#3b1d0f',
      '--semantic-surface-background-secondary': '#5b2a13',
      '--semantic-text-primary': '#fff7ed',
      '--semantic-text-secondary': '#fed7aa',
      '--semantic-text-tertiary': '#fdba74',
    },
  },
  {
    id: 'frog',
    name: 'Frog',
    description: 'Fresh paired theme with lily pad greens and wetland tones',
    author: 'Community',
    sharedTokens: {
      ...standardScaleTokens,
      '--primitive-font-family-sans': '"Comic Neue", "Comic Sans MS", cursive, sans-serif',
      '--primitive-border-radius-sm': '8px',
      '--primitive-border-radius-md': '12px',
      '--primitive-border-radius-lg': '16px',
    },
    lightTokens: {
      '--semantic-brand-primary': '#15803d',
      '--semantic-brand-secondary': '#16a34a',
      '--semantic-brand-primary-subtle': '#dcfce7',
      '--semantic-feedback-success': '#4ade80',
      '--semantic-feedback-warning': '#fbbf24',
      '--semantic-feedback-error': '#ef4444',
      '--semantic-feedback-info': '#06b6d4',
      '--semantic-surface-background': '#f0fdf4',
      '--semantic-surface-card': '#ffffff',
      '--semantic-surface-background-secondary': '#bbf7d0',
      '--semantic-text-primary': '#14532d',
      '--semantic-text-secondary': '#166534',
      '--semantic-text-tertiary': '#4ade80',
    },
    darkTokens: {
      '--semantic-brand-primary': '#4ade80',
      '--semantic-brand-secondary': '#86efac',
      '--semantic-brand-primary-subtle': '#17351f',
      '--semantic-feedback-success': '#22c55e',
      '--semantic-feedback-warning': '#fbbf24',
      '--semantic-feedback-error': '#f87171',
      '--semantic-feedback-info': '#22d3ee',
      '--semantic-surface-background': '#0d1f12',
      '--semantic-surface-card': '#163022',
      '--semantic-surface-background-secondary': '#1f4a30',
      '--semantic-text-primary': '#f0fdf4',
      '--semantic-text-secondary': '#bbf7d0',
      '--semantic-text-tertiary': '#86efac',
    },
  },
  {
    id: 'axolotl',
    name: 'Axolotl',
    description: 'Playful paired theme with pink coral tones and aquatic vibes',
    author: 'Community',
    sharedTokens: {
      ...standardScaleTokens,
      '--primitive-font-family-sans': '"Nunito", "Comic Sans MS", cursive, sans-serif',
      '--primitive-border-radius-sm': '10px',
      '--primitive-border-radius-md': '14px',
      '--primitive-border-radius-lg': '18px',
    },
    lightTokens: {
      '--semantic-brand-primary': '#be185d',
      '--semantic-brand-secondary': '#ec4899',
      '--semantic-brand-primary-subtle': '#fce7f3',
      '--semantic-feedback-success': '#10b981',
      '--semantic-feedback-warning': '#f59e0b',
      '--semantic-feedback-error': '#ef4444',
      '--semantic-feedback-info': '#06b6d4',
      '--semantic-surface-background': '#fdf2f8',
      '--semantic-surface-card': '#ffffff',
      '--semantic-surface-background-secondary': '#fbcfe8',
      '--semantic-text-primary': '#831843',
      '--semantic-text-secondary': '#9f1239',
      '--semantic-text-tertiary': '#f472b6',
    },
    darkTokens: {
      '--semantic-brand-primary': '#f9a8d4',
      '--semantic-brand-secondary': '#f472b6',
      '--semantic-brand-primary-subtle': '#4a1f33',
      '--semantic-feedback-success': '#34d399',
      '--semantic-feedback-warning': '#fbbf24',
      '--semantic-feedback-error': '#f87171',
      '--semantic-feedback-info': '#67e8f9',
      '--semantic-surface-background': '#2a1320',
      '--semantic-surface-card': '#3a1b2c',
      '--semantic-surface-background-secondary': '#4a1f38',
      '--semantic-text-primary': '#fdf2f8',
      '--semantic-text-secondary': '#fbcfe8',
      '--semantic-text-tertiary': '#f9a8d4',
    },
  },
  {
    id: 'smith',
    name: 'Smith',
    description: 'Modern paired theme with refined teal surfaces and crisp spacing',
    author: 'Community',
    sharedTokens: {
      ...standardScaleTokens,
      '--primitive-font-family-sans': '"Manrope", "Segoe UI", sans-serif',
      '--primitive-border-radius-sm': '5px',
      '--primitive-border-radius-md': '8px',
      '--primitive-border-radius-lg': '12px',
    },
    lightTokens: {
      '--semantic-brand-primary': '#0f766e',
      '--semantic-brand-secondary': '#0f766e',
      '--semantic-brand-primary-subtle': '#ccfbf1',
      '--semantic-feedback-success': '#15803d',
      '--semantic-feedback-warning': '#b45309',
      '--semantic-feedback-error': '#dc2626',
      '--semantic-feedback-info': '#0ea5e9',
      '--semantic-surface-background': '#f3fbfa',
      '--semantic-surface-card': '#ffffff',
      '--semantic-surface-background-secondary': '#d9f3ef',
      '--semantic-text-primary': '#123c3a',
      '--semantic-text-secondary': '#2b5c58',
      '--semantic-text-tertiary': '#4f8b83',
    },
    darkTokens: {
      '--semantic-brand-primary': '#5eead4',
      '--semantic-brand-secondary': '#2dd4bf',
      '--semantic-brand-primary-subtle': '#133a39',
      '--semantic-feedback-success': '#4ade80',
      '--semantic-feedback-warning': '#fbbf24',
      '--semantic-feedback-error': '#f87171',
      '--semantic-feedback-info': '#38bdf8',
      '--semantic-surface-background': '#0d1f1d',
      '--semantic-surface-card': '#14302d',
      '--semantic-surface-background-secondary': '#1b4945',
      '--semantic-text-primary': '#e6fffb',
      '--semantic-text-secondary': '#a7f3d0',
      '--semantic-text-tertiary': '#5eead4',
    },
  },
  {
    id: 'dupre',
    name: 'DuPre',
    description: 'Ultra-modern paired theme with saturated purple contrast and sleek geometry',
    author: 'Community',
    sharedTokens: {
      ...standardScaleTokens,
      '--primitive-font-family-sans': '"Sora", "Avenir Next", "Segoe UI", sans-serif',
      '--primitive-border-radius-sm': '4px',
      '--primitive-border-radius-md': '7px',
      '--primitive-border-radius-lg': '12px',
      '--primitive-font-size-lg': '1.2rem',
    },
    lightTokens: {
      '--semantic-brand-primary': '#6d28d9',
      '--semantic-brand-secondary': '#7c3aed',
      '--semantic-brand-primary-subtle': '#ede9fe',
      '--semantic-feedback-success': '#15803d',
      '--semantic-feedback-warning': '#b45309',
      '--semantic-feedback-error': '#dc2626',
      '--semantic-feedback-info': '#2563eb',
      '--semantic-surface-background': '#faf8ff',
      '--semantic-surface-card': '#ffffff',
      '--semantic-surface-background-secondary': '#e9ddff',
      '--semantic-text-primary': '#2e1065',
      '--semantic-text-secondary': '#5b21b6',
      '--semantic-text-tertiary': '#8b5cf6',
    },
    darkTokens: {
      '--semantic-brand-primary': '#c4b5fd',
      '--semantic-brand-secondary': '#a78bfa',
      '--semantic-brand-primary-subtle': '#2b1d53',
      '--semantic-feedback-success': '#4ade80',
      '--semantic-feedback-warning': '#fbbf24',
      '--semantic-feedback-error': '#f87171',
      '--semantic-feedback-info': '#60a5fa',
      '--semantic-surface-background': '#140f23',
      '--semantic-surface-card': '#1f1733',
      '--semantic-surface-background-secondary': '#342353',
      '--semantic-text-primary': '#f5f3ff',
      '--semantic-text-secondary': '#ddd6fe',
      '--semantic-text-tertiary': '#c4b5fd',
    },
  },
  {
    id: 'puckett',
    name: 'Puckett',
    description: 'Rounded paired theme with soft lavender tones and friendly depth',
    author: 'Community',
    sharedTokens: {
      ...standardScaleTokens,
      '--primitive-font-family-sans': '"Nunito Sans", "Segoe UI", sans-serif',
      '--primitive-border-radius-sm': '10px',
      '--primitive-border-radius-md': '14px',
      '--primitive-border-radius-lg': '20px',
    },
    lightTokens: {
      '--semantic-brand-primary': '#7c3aed',
      '--semantic-brand-secondary': '#8b5cf6',
      '--semantic-brand-primary-subtle': '#f3e8ff',
      '--semantic-feedback-success': '#15803d',
      '--semantic-feedback-warning': '#b45309',
      '--semantic-feedback-error': '#dc2626',
      '--semantic-feedback-info': '#2563eb',
      '--semantic-surface-background': '#faf5ff',
      '--semantic-surface-card': '#ffffff',
      '--semantic-surface-background-secondary': '#e9d5ff',
      '--semantic-text-primary': '#4c1d95',
      '--semantic-text-secondary': '#6d28d9',
      '--semantic-text-tertiary': '#a78bfa',
    },
    darkTokens: {
      '--semantic-brand-primary': '#c4b5fd',
      '--semantic-brand-secondary': '#ddd6fe',
      '--semantic-brand-primary-subtle': '#33204f',
      '--semantic-feedback-success': '#4ade80',
      '--semantic-feedback-warning': '#fbbf24',
      '--semantic-feedback-error': '#f87171',
      '--semantic-feedback-info': '#60a5fa',
      '--semantic-surface-background': '#1a1228',
      '--semantic-surface-card': '#261836',
      '--semantic-surface-background-secondary': '#37214f',
      '--semantic-text-primary': '#faf5ff',
      '--semantic-text-secondary': '#e9d5ff',
      '--semantic-text-tertiary': '#d8b4fe',
    },
  },
  {
    id: 'xayavong',
    name: 'Xayavong',
    description: 'Semi-rounded paired theme with grounded forest greens and calm structure',
    author: 'Community',
    sharedTokens: {
      ...standardScaleTokens,
      '--primitive-font-family-sans': '"Public Sans", "Segoe UI", sans-serif',
      '--primitive-border-radius-sm': '6px',
      '--primitive-border-radius-md': '10px',
      '--primitive-border-radius-lg': '14px',
    },
    lightTokens: {
      '--semantic-brand-primary': '#166534',
      '--semantic-brand-secondary': '#15803d',
      '--semantic-brand-primary-subtle': '#dcfce7',
      '--semantic-feedback-success': '#15803d',
      '--semantic-feedback-warning': '#b45309',
      '--semantic-feedback-error': '#dc2626',
      '--semantic-feedback-info': '#0284c7',
      '--semantic-surface-background': '#f3faf5',
      '--semantic-surface-card': '#ffffff',
      '--semantic-surface-background-secondary': '#d7efe0',
      '--semantic-text-primary': '#123524',
      '--semantic-text-secondary': '#20563c',
      '--semantic-text-tertiary': '#4d8b6e',
    },
    darkTokens: {
      '--semantic-brand-primary': '#86efac',
      '--semantic-brand-secondary': '#4ade80',
      '--semantic-brand-primary-subtle': '#17351f',
      '--semantic-feedback-success': '#4ade80',
      '--semantic-feedback-warning': '#fbbf24',
      '--semantic-feedback-error': '#f87171',
      '--semantic-feedback-info': '#38bdf8',
      '--semantic-surface-background': '#0f1c14',
      '--semantic-surface-card': '#16281d',
      '--semantic-surface-background-secondary': '#213b2b',
      '--semantic-text-primary': '#f0fdf4',
      '--semantic-text-secondary': '#bbf7d0',
      '--semantic-text-tertiary': '#86efac',
    },
  },
  {
    id: 'greaff',
    name: 'Greaff',
    description: 'Rounded paired theme with matcha greens and soft tactile surfaces',
    author: 'Community',
    sharedTokens: {
      ...standardScaleTokens,
      '--primitive-font-family-sans': '"Quicksand", "Segoe UI", sans-serif',
      '--primitive-border-radius-sm': '10px',
      '--primitive-border-radius-md': '14px',
      '--primitive-border-radius-lg': '20px',
    },
    lightTokens: {
      '--semantic-brand-primary': '#4d7c0f',
      '--semantic-brand-secondary': '#65a30d',
      '--semantic-brand-primary-subtle': '#ecfccb',
      '--semantic-feedback-success': '#3f6212',
      '--semantic-feedback-warning': '#b45309',
      '--semantic-feedback-error': '#dc2626',
      '--semantic-feedback-info': '#0284c7',
      '--semantic-surface-background': '#fafdf3',
      '--semantic-surface-card': '#ffffff',
      '--semantic-surface-background-secondary': '#e6f5c8',
      '--semantic-text-primary': '#365314',
      '--semantic-text-secondary': '#4d7c0f',
      '--semantic-text-tertiary': '#84cc16',
    },
    darkTokens: {
      '--semantic-brand-primary': '#bef264',
      '--semantic-brand-secondary': '#a3e635',
      '--semantic-brand-primary-subtle': '#263414',
      '--semantic-feedback-success': '#86efac',
      '--semantic-feedback-warning': '#fbbf24',
      '--semantic-feedback-error': '#f87171',
      '--semantic-feedback-info': '#38bdf8',
      '--semantic-surface-background': '#171e0e',
      '--semantic-surface-card': '#212b13',
      '--semantic-surface-background-secondary': '#36451f',
      '--semantic-text-primary': '#f7fee7',
      '--semantic-text-secondary': '#d9f99d',
      '--semantic-text-tertiary': '#bef264',
    },
  },
  {
    id: 'simpson',
    name: 'Simpson',
    description: 'Modern paired theme with royal blues and clear editorial contrast',
    author: 'Community',
    sharedTokens: {
      ...standardScaleTokens,
      '--primitive-font-family-sans': '"IBM Plex Sans", "Segoe UI", sans-serif',
      '--primitive-border-radius-sm': '4px',
      '--primitive-border-radius-md': '8px',
      '--primitive-border-radius-lg': '12px',
    },
    lightTokens: {
      '--semantic-brand-primary': '#1d4ed8',
      '--semantic-brand-secondary': '#2563eb',
      '--semantic-brand-primary-subtle': '#dbeafe',
      '--semantic-feedback-success': '#15803d',
      '--semantic-feedback-warning': '#b45309',
      '--semantic-feedback-error': '#dc2626',
      '--semantic-feedback-info': '#0284c7',
      '--semantic-surface-background': '#f5f8ff',
      '--semantic-surface-card': '#ffffff',
      '--semantic-surface-background-secondary': '#d9e7ff',
      '--semantic-text-primary': '#172554',
      '--semantic-text-secondary': '#1e40af',
      '--semantic-text-tertiary': '#60a5fa',
    },
    darkTokens: {
      '--semantic-brand-primary': '#93c5fd',
      '--semantic-brand-secondary': '#60a5fa',
      '--semantic-brand-primary-subtle': '#18294f',
      '--semantic-feedback-success': '#4ade80',
      '--semantic-feedback-warning': '#fbbf24',
      '--semantic-feedback-error': '#f87171',
      '--semantic-feedback-info': '#38bdf8',
      '--semantic-surface-background': '#0f172b',
      '--semantic-surface-card': '#152040',
      '--semantic-surface-background-secondary': '#223564',
      '--semantic-text-primary': '#eff6ff',
      '--semantic-text-secondary': '#bfdbfe',
      '--semantic-text-tertiary': '#93c5fd',
    },
  },
  {
    id: 'garrett',
    name: 'Garrett',
    description: 'Edgy paired theme with deep ceremonial blues and sharper corners',
    author: 'Community',
    sharedTokens: {
      ...standardScaleTokens,
      '--primitive-font-family-sans': '"Rajdhani", "Segoe UI", sans-serif',
      '--primitive-border-radius-sm': '2px',
      '--primitive-border-radius-md': '4px',
      '--primitive-border-radius-lg': '8px',
      '--primitive-font-size-lg': '1.2rem',
    },
    lightTokens: {
      '--semantic-brand-primary': '#1e3a8a',
      '--semantic-brand-secondary': '#1d4ed8',
      '--semantic-brand-primary-subtle': '#dbeafe',
      '--semantic-feedback-success': '#15803d',
      '--semantic-feedback-warning': '#b45309',
      '--semantic-feedback-error': '#dc2626',
      '--semantic-feedback-info': '#0369a1',
      '--semantic-surface-background': '#f4f7ff',
      '--semantic-surface-card': '#ffffff',
      '--semantic-surface-background-secondary': '#d5def7',
      '--semantic-text-primary': '#0f172a',
      '--semantic-text-secondary': '#172554',
      '--semantic-text-tertiary': '#3b82f6',
    },
    darkTokens: {
      '--semantic-brand-primary': '#93c5fd',
      '--semantic-brand-secondary': '#60a5fa',
      '--semantic-brand-primary-subtle': '#142347',
      '--semantic-feedback-success': '#4ade80',
      '--semantic-feedback-warning': '#fbbf24',
      '--semantic-feedback-error': '#f87171',
      '--semantic-feedback-info': '#38bdf8',
      '--semantic-surface-background': '#0b1226',
      '--semantic-surface-card': '#111a35',
      '--semantic-surface-background-secondary': '#1b2b57',
      '--semantic-text-primary': '#eff6ff',
      '--semantic-text-secondary': '#cbd5e1',
      '--semantic-text-tertiary': '#93c5fd',
    },
  },
];

export const THEME_PRESETS: ThemePreset[] = themePresetDefinitions.map(createThemePreset);
